title: Simone Caldarella
position: AI Engineer
logo: /assets/img/logo.jpg
logo_caption: Me at Parc du Cinquantenaire, <br> Brussels 2022
description: I have no special talent. I am only passionately curious.
show_downloads: false
theme: jekyll-theme-minimal
github: SimoneCaldarella
